export const enviroment = {
    BUSINESS_NAME: process.env.REACT_APP_BUSINESS_NAME,
    PRIMARY_COLOR: process.env.REACT_APP_PRIMARY_COLOR,
    SECONDARY_COLOR: process.env.REACT_APP_SECONDARY_COLOR,
    MENU_HOVER_COLOR: process.env.REACT_APP_MENU_HOVER_COLOR,
    ADD_BUTTON_COLOR: process.env.REACT_APP_ADD_BUTTON_COLOR,
    SEARCH_PLACEHOLDER: process.env.REACT_APP_SEARCH_PLACEHOLDER,
    PHONE_NUMBER: process.env.REACT_APP_PHONE_NUMBER,
    EMAIL_ADDRESS: process.env.REACT_APP_EMAIL_ADDRESS,
    FACEBOOK_LINK: process.env.REACT_APP_FACEBOOK_LINK,
    INSTAGRAM_LINK: process.env.REACT_APP_INSTAGRAM_LINK,
    TWITTER_LINK: process.env.REACT_APP_TWITTER_LINK,
    LINKEDIN_LINK: process.env.REACT_APP_LINKEDIN_LINK,
}